apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatekeeper
  template:
    metadata:
      labels:
        app: gatekeeper
    spec:
      containers:
      - name: gatekeeper
        image: northamerica-northeast1-docker.pkg.dev/kubernetes-assignment-417316/cloud-assignment/gatekeeper:latest
        ports:
        - containerPort: 6000
        volumeMounts:
        - mountPath: /nikunj_PV_dir
          name: persistent-storage
        env:
        - name: CONTAINER2_URL
          value: "http://processor-service.default.svc.cluster.local:3000"
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: pv-claim
